SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{69AE77F44F625F31}" {
   m_sEntityPrefab "{2CDCFF4237E63650}Prefabs/Weapons/Attachments/Muzzle/Suppressor_9mm_placeholder.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69AE77F44F625FE0}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 20
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{69AE77F45F16E1AC}" {
   m_sEntityPrefab "{6288A1F1A5E3AC38}Prefabs/Weapons/Attachments/Muzzle/MP5K-PDW Thread_cap.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69AE77F45F16E0C1}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 1
     m_eRequiredRank CAPTAIN
    }
   }
  }
 }
}