SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{69A8B35FEBD006EF}" {
   m_sEntityPrefab "{FD0DE25AC213EC9F}Prefabs/Weapons/Rifles/MP5/Rifle_MP5K-PDW.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69A8B35FEBD0069D}" {
     m_eItemMode WEAPON
     m_iSupplyCost 25
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{69AC531617C5BA25}" {
   m_sEntityPrefab "{E08D76FE59F3DE0E}Prefabs/Weapons/Rifles/MP5/Rifle_MP5K-PDW Suppressor.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69AC531617C5BAD4}" {
     m_eItemMode WEAPON
     m_iSupplyCost 40
     m_eRequiredRank LIEUTENANT
    }
   }
  }
 }
}