SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{664928B112267D7B}" {
     m_sEntityPrefab "{15D61BB37FF344B4}Prefabs/Characters/HeadGear/ARY_Helmet_M1_01/ARY_Helmet_M1_01_Cover_NoChinCup_M81_Woodland.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{664928B112267D2A}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 2
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{664928B112B69816}" {
     m_sEntityPrefab "{A3F1FC623A0B5A7D}Prefabs/Characters/HeadGear/ARY_Helmet_M1_01/ARY_Helmet_M1_01_Cover_NoChinCup_Mitchell_Leaf.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{664928B112B69BD3}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 2
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{664928B12D67FDFC}" {
     m_sEntityPrefab "{54765DF450BCA077}Prefabs/Characters/HeadGear/ARY_Helmet_M1_01/ARY_Helmet_M1_01_Cover_NoChinCup_Mitchell_Clouds.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{664928B12D67FDB1}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 2
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{664928B12C0104E1}" {
     m_sEntityPrefab "{159C5E553764E8FD}Prefabs/Characters/HeadGear/ARY_Helmet_M1_01/ARY_Helmet_M1_01_Cover_NoChinCup_ERDL_RDF.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{664928B12C0104A6}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 2
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66C745CD6B8C25FB}" {
     m_sEntityPrefab "{4F9529FA4AFEB083}Prefabs/Characters/HeadGear/ARY_Helmet_M1_01/ARY_Helmet_M1_01_Cover_NoChinCup_TigerStripe.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66C745CD6B8C3FD4}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 2
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66C94E18C75888BF}" {
     m_sEntityPrefab "{81CB507191E5BBC7}Prefabs/Characters/HeadGear/ARY_Helmet_M1_01/ARY_Helmet_M1_01_Cover_NoChinCup_Frogskin.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66C94E18C758880B}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 2
       m_eRequiredRank SERGEANT
      }
     }
    }
   }
  }
 }
}