SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{668730879AB8AF53}" {
   m_sEntityPrefab "{2E4873E2CEC9A254}Prefabs/Characters/Factions/BLUFOR/US_Army/ARY_Character_US_Crew_M3A1.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{668730879AB8A57F}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{668730879578538C}" {
   m_sEntityPrefab "{5DDD8204F4C81938}Prefabs/Characters/Factions/BLUFOR/US_Army/ARY_Character_US_CC_M3A1.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{668730879578537B}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{66873087973366EC}" {
   m_sEntityPrefab "{F9EAB42FC4028AB3}Prefabs/Characters/Factions/BLUFOR/US_Army/ARY_Character_US_SF_M3A1_S.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{668730879733665F}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6687308797336651}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}