SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Deployables - All (British Forces)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{6676DAB91C58C013}" {
   m_sEntityPrefab "{368C6A5B79779B77}Prefabs/Items/Equipment/Tripods/M2/Part_M2_Gun_UK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{61ECC6DC8DB987BC}" {
     m_eItemType EQUIPMENT
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 80
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6676DAB9189A362D}" {
   m_sEntityPrefab "{B5528AFBA2E014FE}Prefabs/Items/Equipment/Tripods/M2/Part_M3_Tripod_UK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6556A2FFDA3E5050}" {
     m_eItemType EQUIPMENT
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 40
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6676DAB930BAC2DF}" {
   m_sEntityPrefab "{0F22B7FD230E4134}Prefabs/Items/Equipment/Mortars/M252/Part_L16_BasePlate_UK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6556A2FFC51E27EA}" {
     m_eItemType EQUIPMENT
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 90
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6676DAB933D30C39}" {
   m_sEntityPrefab "{C7E4690A8614F9B2}Prefabs/Items/Equipment/Mortars/M252/Part_L16_Bipod_UK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6556A2FFC43882D0}" {
     m_eItemType EQUIPMENT
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 90
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6676DAB932835DDC}" {
   m_sEntityPrefab "{C6A179FF42B6C692}Prefabs/Items/Equipment/Mortars/M252/Part_L16_Barrel_UK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6556A2FFD34470B0}" {
     m_eItemType EQUIPMENT
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 90
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6676DAB9177AE10C}" {
   m_sEntityPrefab "{1F3B04D389581161}Prefabs/Items/Equipment/Tripods/M60/Part_Tripod_M122_UK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6556B93806ADFA2E}" {
     m_eItemType EQUIPMENT
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 30
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6676DAB95E861D51}" {
   m_sEntityPrefab "{36F53E43721F69DA}Prefabs/Items/Misc/Sandbags/Part_Sandbag_Burlap_UK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{65DCB44115EC3D83}" {
     m_eItemType EQUIPMENT
     m_eItemMode SUPPORT_STATION
     m_iSupplyCost 2
    }
   }
  }
 }
}