SystemSettings {
 Systems {
  RT_PS_CustomRadioAntennaSystem "{64A2F5DFFB07E25F}" {
   Enabled 0
  }
  RT_PS_CustomRadioAntennaSystem "{69C8D78B7B4F5000}" {
   m_aRadiostations {
    RT_PS_CustomRadioStation "{64A30682673CADE3}" {
     m_sRadiostationName "Radio Semer la Discord"
     m_StationAudioProject "{B31B79C3019C3AF2}Sounds/RadioBroadcast/ServRadioBroadcast.acp"
     m_aTracksLengths {
      57
      59
     }
     m_aTracksNames {
      "AMAT Reforgé - FM Edition"
      "AMAT Reforgé - Unknown Edition"
     }
     m_fDjProbability 0
    }
    RT_PS_CustomRadioStation "{69C8D78B5C02B34F}" {
     m_sRadiostationName "Radio AMAT"
     m_StationAudioProject "{E7ED325544EC55D3}Sounds/RadioBroadcast/AMATRadioBroadcast.acp"
     m_aTracksLengths {
      222
      178
      196
      273
      164
     }
     m_aTracksNames {
      "BTR en feu"
      "J'entend le loot..."
      "Le Barde va Prompter"
      "Rage Against The Modding - Galère la radio"
      "Ural Brutal"
     }
     m_fDjProbability 0
    }
    RT_PS_CustomRadioStation "{69C8D78B5D490017}" {
     m_sRadiostationName "Radio Cirés Jaunes"
     m_StationAudioProject "{EC8885318CD72BA5}Sounds/RadioBroadcast/JauneRadioBroadcast.acp"
     m_aTracksLengths {
      214
      175
      169
      196
      439
      276
     }
     m_aTracksNames {
      "deus da enrollañ"
      "Code Jaune !"
      "Hymne des Cirés Jaunes à Kolguyev"
      "Hymne Métal des Cirés Jaunes"
      "La libération de Mineraly"
      "Yellow Raincoats"
     }
     m_fDjProbability 0
    }
   }
  }
 }
}