SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453CE20F8F}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{667330FBAAE52A5C}" {
     m_sEntityPrefab "{500B6C93BDF56853}Prefabs/Weapons/Launchers/ARY_M79/ARY_Launcher_M79_Wood_M406.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{667330FBE0CAE6B5}" {
       m_eItemType ROCKET_LAUNCHER
       m_eItemMode WEAPON
       m_iSupplyCost 5
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{667330FBE0CAE6B7}" {
         m_vItemOffset 0 0 -0.2
        }
       }
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C630E4538D3163D}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{667330FBBAE8BE10}" {
     m_sEntityPrefab "{5375FA7CB1F68573}Prefabs/Weapons/Ammo/Ammo_Grenade_HE_M406.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C62F7D84B59D2FC}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 3
      }
     }
    }
   }
  }
 }
}