SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{6606CA5A6622CE0D}" {
   m_sEntityPrefab "{EFDFFB97FA256A0A}Prefabs/Weapons/Attachments/Bayonets/ARY_Bayonet_G3.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{60A8A26936DFFC1D}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}