SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{668AFB24F6D9363B}" {
     m_sEntityPrefab "{804D55B3B293D81B}Prefabs/Characters/Uniforms/ARY_BDU_ERDL_Green/ARY_BDU_Jacket_ERDL_Green.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{668AFB24F6DAC9EB}" {
       m_eItemType TORSO
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{668AFB24F61045AC}" {
     m_sEntityPrefab "{73F70BF5923FA08F}Prefabs/Characters/Uniforms/ARY_BDU_ERDL_Green/ARY_BDU_Jacket_RolledUp_ERDL_Green.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{668AFB24F610451E}" {
       m_eItemType TORSO
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{668AFB24F76B16DF}" {
     m_sEntityPrefab "{BFD191F4A79B9D0F}Prefabs/Characters/Uniforms/ARY_BDU_ERDL_Green/ARY_BDU_Pants_ERDL_Green.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{668AFB24F76B16B5}" {
       m_eItemType TORSO
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{668AFB24F0135AD3}" {
     m_sEntityPrefab "{497EAF9E9283837F}Prefabs/Characters/HeadGear/ARY_Helmet_Skate_01/ARY_Helmet_Skate_01.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{668AFB24F0135A8D}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 5
       m_eRequiredRank LIEUTENANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{668AC983D184EF0A}" {
     m_sEntityPrefab "{416C8FB0BEE55558}Prefabs/Characters/Uniforms/ARY_Jacket_US_BDU_02_Black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{668AC983D184EEEE}" {
       m_eItemType TORSO
       m_iSupplyCost 0
       m_eRequiredRank LIEUTENANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{668AC983EFFA33B0}" {
     m_sEntityPrefab "{16F681496BE92D7E}Prefabs/Characters/Uniforms/ARY_Pants_Jeans/ARY_Pants_Jeans_Blue.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{668AC983EFFA3375}" {
       m_eItemType LEGS
       m_iSupplyCost 0
       m_eRequiredRank LIEUTENANT
      }
     }
    }
   }
  }
 }
}