SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{663525F90871807D}" {
   m_sEntityPrefab "{707D23B79A8DE5BC}Prefabs/Characters/Factions/BLUFOR/US_Army/ARY_Character_US_Rifleman_M14.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6618DB079E44ED34}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6618DB079E44ED36}" {
     m_eSlotTypes GROUP_SMALL
    }
    SCR_EntityCatalogLoadoutData "{6618DB079E44ED28}" {
     m_fSpawnSupplyCost 20
    }
   }
  }
  SCR_EntityCatalogEntry "{663525F90BE692F6}" {
   m_sEntityPrefab "{BB9C1CFB30A3EC43}Prefabs/Characters/Factions/BLUFOR/US_Army/GreenBerets/ARY_Character_US_SF_M14.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{66252720EB8CE673}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{66252720EB8CE676}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}