SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{692CCD8EB9DF8CA5}" {
   m_sEntityPrefab "{B920961E143649E6}Prefabs/Characters/Campaign/Final/RNGD/Campaign_RNGD_Player.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{692CCD8EB9DF8CBD}" {
     m_eValidEditorModes 0
    }
    SCR_EntityCatalogLoadoutData "{692CCD8EFD43844C}" {
     m_fSpawnSupplyCost 0
     m_eRequiredRank RENEGADE
    }
   }
  }
 }
}