SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{67190D14D3FE5D98}" {
   m_sEntityPrefab "{3E158E1B65E804F9}Prefabs/Characters/Factions/OPFOR/USSR_Army/ARY_Character_USSR_Rifleman_Reservist_AKM.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{67190D14D3FE5D15}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{67190D14D3FE5D08}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{67190D14EE5417AA}" {
   m_sEntityPrefab "{978E50519998BC8C}Prefabs/Characters/Factions/OPFOR/USSR_Army/ARY_Character_USSR_AR_Reservist_RPK.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{67190D14EE541764}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{67190D14EE541719}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{67190D14E7933B4E}" {
   m_sEntityPrefab "{94BD0BC2A87145EB}Prefabs/Characters/Factions/OPFOR/USSR_Army/Spetsnaz/Suppressed/ARY_Character_USSR_SF_S_AKM.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{67190D14E7933B3C}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{67190D14E7933B3E}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}