SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{668A96BB0EF6EADC}" {
   m_sEntityPrefab "{E7E46292F7EC7AA1}Prefabs/Weapons/Rifles/ARY_M3A1/ARY_Rifle_M3A1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66873087AF2056A9}" {
     m_eItemMode WEAPON
     m_iSupplyCost 2
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66873087AF2056AA}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668A96BB0876CAE2}" {
   m_sEntityPrefab "{D95E7F79ECCB607A}Prefabs/Weapons/Rifles/ARY_M3A1/ARY_Rifle_M3A1_FlashHider.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66873087AF2056A9}" {
     m_eItemMode WEAPON
     m_iSupplyCost 2
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66873087AF2056AA}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668A96BB1AA44858}" {
   m_sEntityPrefab "{B3143A9149BBC9A7}Prefabs/Weapons/Rifles/ARY_M3A1/ARY_Rifle_M3A1_FlashHider_FlashLight.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668A96BB1AA4480A}" {
     m_eItemMode WEAPON
     m_iSupplyCost 2
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{668A96BB1AA4480C}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668A96BB11E12E22}" {
   m_sEntityPrefab "{AE93DCA48044E3B9}Prefabs/Weapons/Rifles/ARY_M3A1/ARY_Rifle_M3A1_Suppressor.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668A96BB11E12194}" {
     m_eItemMode WEAPON
     m_iSupplyCost 2
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{668A96BB11E12197}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668A96BB13F26189}" {
   m_sEntityPrefab "{182B6331B5A32C40}Prefabs/Weapons/Rifles/ARY_M3A1/ARY_Rifle_M3A1_Suppressor_FlashLight.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668A96BB13F26177}" {
     m_eItemMode WEAPON
     m_iSupplyCost 2
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{668A96BB13F2616A}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668A96BB2CF9E525}" {
   m_sEntityPrefab "{6DE8D9757C3E417E}Prefabs/Weapons/Rifles/ARY_M3A1/ARY_Rifle_M3A1_Worn.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668A96BB2CF9E492}" {
     m_eItemMode WEAPON
     m_iSupplyCost 2
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{668A96BB2CF9E494}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668A96BB09FD1758}" {
   m_sEntityPrefab "{2B11B56657049511}Prefabs/Weapons/Rifles/ARY_M3A1/ARY_Rifle_M3A1_BurpGun.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66873087AF2056A9}" {
     m_eItemMode WEAPON
     m_iSupplyCost 2
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66873087AF2056AA}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
 }
}