SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{663934CED2F0655F}" {
   m_sEntityPrefab "{12F819651BEEFECB}Prefabs/Weapons/Magazines/ARY_Magazine_556x45_M16_20rnd_M193_Ball.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663933F8D2B1A49A}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663934CEEDA57485}" {
   m_sEntityPrefab "{4BB3203E36D0E163}Prefabs/Weapons/Magazines/ARY_Magazine_556x45_M16_20rnd_M193_M196_Last_5Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663933F8ED9BC530}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663934CEEC217DBD}" {
   m_sEntityPrefab "{A3C8CF7C695D24DE}Prefabs/Weapons/Magazines/ARY_Magazine_556x45_M16_20rnd_M196_Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663933F8EC5DBA71}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663D30047A76BF99}" {
   m_sEntityPrefab "{8A92B165361ADAF1}Prefabs/Weapons/Magazines/ARY_Magazine_556x45_M16_20rnd_Surplus_Ball.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663D30047A76BFD3}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663D30047BE437EC}" {
   m_sEntityPrefab "{5AC40AE764891215}Prefabs/Weapons/Magazines/ARY_Magazine_556x45_M16_20rnd_Surplus_Last_5Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663D30047BE4371E}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663D30047B4DC87F}" {
   m_sEntityPrefab "{50EC00FDD757E1E0}Prefabs/Weapons/Magazines/ARY_Magazine_556x45_M16_20rnd_Surplus_Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663D30047B4E37B0}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6639368A8A2C5F1B}" {
   m_sEntityPrefab "{FB5EB0F6D447E858}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M193_Ball.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6639368851925E81}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6639368A85316885}" {
   m_sEntityPrefab "{7ECA478D7C80ACC0}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M193_M196_Last_5Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663936886DB76AAE}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6639368A8B5BEB2B}" {
   m_sEntityPrefab "{4575737B3D3A4505}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M196_Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663936886848678F}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663D3004570F292B}" {
   m_sEntityPrefab "{0BD7415A0CA7A300}Prefabs/Weapons/Magazines/ARY_Magazine_556x45_STANAG_30rnd_Surplus_Ball.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663D3004570F2956}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663D300457C2E600}" {
   m_sEntityPrefab "{19D36F1BAFC78117}Prefabs/Weapons/Magazines/ARY_Magazine_556x45_STANAG_30rnd_Surplus_Last_5Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663D300457C2E5B4}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663D3004567A2974}" {
   m_sEntityPrefab "{6E9F9EAAF97252A0}Prefabs/Weapons/Magazines/ARY_Magazine_556x45_STANAG_30rnd_Surplus_Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663D3004567A28A3}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
 }
}