SCR_EntityCatalog {
 m_eEntityCatalogType WEAPONS_TRIPOD
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{5C54F92F783BF0ED}" {
   m_sEntityPrefab "{723870DBB19D30B0}Prefabs/Weapons/Tripods/Tripod_6T5_PKM.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{60569781395F8C0E}" {
     m_bEnabled 0
    }
   }
  }
 }
}