SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{671CE534C243A943}" {
   m_sEntityPrefab "{A82756201C83C245}Prefabs/Weapons/Rifles/ARY_AKM/ARY_Rifle_AKM.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66CEF238775A1F92}" {
     m_eItemMode WEAPON
     m_iSupplyCost 5
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66CEF238775A1F94}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534D131694F}" {
   m_sEntityPrefab "{DF36ADC5B3BBA6DA}Prefabs/Weapons/Rifles/ARY_AKM/Optic Rail/ARY_Rifle_AKMN.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{671745A89B02BD79}" {
     m_eItemMode WEAPON
     m_iSupplyCost 40
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{671745A89B02BD7E}" {
       m_vItemOffset 0 0 -0.2
      }
     }
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534D7C920D7}" {
   m_sEntityPrefab "{CE7A75DD6AEC156D}Prefabs/Weapons/Rifles/ARY_AKM/ARY_Rifle_AKMS.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66A6C1F0EBE86649}" {
     m_eItemMode WEAPON
     m_iSupplyCost 7
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66A6C1F0EBE8664E}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534D1CF7C24}" {
   m_sEntityPrefab "{540718B8A82BD302}Prefabs/Weapons/Rifles/ARY_AKM/Optic Rail/ARY_Rifle_AKMSN.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{671745A89BE26674}" {
     m_eItemMode WEAPON
     m_iSupplyCost 45
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{671745A89BE26676}" {
       m_vItemOffset 0 0 -0.2
      }
     }
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534F50648AF}" {
   m_sEntityPrefab "{319226CEB82961A9}Prefabs/Weapons/Rifles/ARY_AKM/ARY_Rifle_AKMS_Folded.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{671CE534F506678B}" {
     m_eItemMode WEAPON
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{671CE534F5066784}" {
       m_vItemOffset 0 0 -0.12
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534FFB7C47F}" {
   m_sEntityPrefab "{8F0807ABED77AEDE}Prefabs/Weapons/Rifles/ARY_AKM/ARY_Rifle_AKM_scav.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{67132184DBC6378C}" {
     m_eItemMode WEAPON
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{67132184DBC6378E}" {
       m_vItemOffset 0 0 -0.12
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534D6798695}" {
   m_sEntityPrefab "{6A7FF4C51334EA4D}Prefabs/Weapons/Rifles/ARY_AKM/ARY_Rifle_RPK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66A6C1F0F868E33B}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 15
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66A6C1F0F868E33D}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534D0697490}" {
   m_sEntityPrefab "{B38FB100A8AD161A}Prefabs/Weapons/Rifles/ARY_AKM/Optic Rail/ARY_Rifle_RPKN.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6716F8752DF8A6A7}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 50
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{6716F8752DF8A65A}" {
       m_vItemOffset 0 0 -0.2
      }
     }
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534FCFB8F70}" {
   m_sEntityPrefab "{78AB14214ED62F38}Prefabs/Weapons/Rifles/ARY_AKM/ARY_Rifle_AK_47.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{67132184C01C6165}" {
     m_eItemMode WEAPON
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{67132184C01C6167}" {
       m_vItemOffset 0 0 -0.12
      }
     }
    }
   }
  }
 }
}