SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{660F40618D0C270D}" {
   m_sEntityPrefab "{DB14946F5472DA61}Prefabs/Weapons/Attachments/Optics/ARY_Optic_APElectronic/ARY_Collim_APElectronic.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{606084A3AC514F5E}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6606BD0F225EADD6}" {
   m_sEntityPrefab "{B1E7EB3C41C63E23}Prefabs/Weapons/Attachments/Optics/ARY_Optic_ZF4/ARY_Optic_Z24_4x_Worn.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{5C62F7D8680EBEA9}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 26
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{660B2E97BFF82153}" {
   m_sEntityPrefab "{A78EF315BE900C23}Prefabs/Weapons/Attachments/Optics/ARY_Optic_ZF4/ARY_Optic_Z24_4x.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{660B2E97BFF8211B}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 32
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{660B2E97BE82043C}" {
   m_sEntityPrefab "{12A4EED229D44180}Prefabs/Weapons/Attachments/Optics/ARY_Optic_ZF4/ARY_Optic_Z24_4x_Quality.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{660B2E97BE8207C7}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 38
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6606BD0F3435FF67}" {
   m_sEntityPrefab "{03E8553297A72CCA}Prefabs/Weapons/Attachments/Optics/ARY_Optic_SG1/ARY_Optic_G3_DA_1-5_6x.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{5C62F7D86AED1F20}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 75
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6612884B011CA661}" {
   m_sEntityPrefab "{B8A2547514B6F9FF}Prefabs/Weapons/Attachments/Optics/ARY_Optic_Flashlight_ClawMount/ARY_Flashlight_Clawmount.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6612884B011CB9DE}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 15
     m_eRequiredRank SERGEANT
    }
   }
  }
 }
}