SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{61069305DC40022E}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{61069305C2E48611}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{60DCAD0E3D25D905}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{61069305C13A7156}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{6108A91CBF7C8645}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{6108A91CBDE7D74F}" {
   m_bEnabled 0
  }
  SCR_EntityCatalogEntry "{6108A91CA3BA089E}" {
   m_bEnabled 0
  }
 }
}