SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{66C2A30AD37D66D8}" {
   m_sEntityPrefab "{B82489DA7ECBD22D}Prefabs/Weapons/Attachments/Bayonets/ARY_Bayonet_UZI.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C2A30ADE33879A}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6690FD4788473FFA}" {
   m_sEntityPrefab "{D0E58ADBD6B74289}Prefabs/Weapons/Attachments/Muzzle/ARY_Suppressor_UZI/ARY_Suppressor_UZI_Worn.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6690FD43A8C23D86}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6690FD478A77898C}" {
   m_sEntityPrefab "{253CE111B38E95D1}Prefabs/Weapons/Attachments/Muzzle/ARY_Suppressor_UZI/ARY_Suppressor_UZI.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6690FD478A778974}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6690FD478532239E}" {
   m_sEntityPrefab "{68A6EF20AB615640}Prefabs/Weapons/Attachments/Muzzle/ARY_Suppressor_UZI/ARY_Suppressor_UZI_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6690FD478532234C}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66C2A30AE696D78B}" {
   m_sEntityPrefab "{B732A5409344F18E}Prefabs/Weapons/Attachments/Bayonets/ARY_Laser_UZI.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{669D2DB1E5B26444}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_eRequiredRank SERGEANT
    }
   }
  }
 }
}