SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{609E851E98807F03}" {
     m_sEntityPrefab "{ED492F11FCFAE30A}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_4x20_OliveGreen_Sand_Stripes.et"
    }
    SCR_EntityCatalogInventoryItem "{659303CEE4E4AB3F}" {
     m_sEntityPrefab "{E57DBDA5C50F07FF}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine_4x20.et"
    }
    SCR_EntityCatalogInventoryItem "{659303CE8FBAECC8}" {
     m_sEntityPrefab "{B1482FB64E3D2D45}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_4x20.et"
    }
    SCR_EntityCatalogInventoryItem "{659303CEF3348A3F}" {
     m_sEntityPrefab "{60B4E42557D61CF9}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_4x20_OliveGreen_Solid.et"
    }
    SCR_EntityCatalogInventoryItem "{659303C91B1834D6}" {
     m_sEntityPrefab "{92A0764C4EDF7C14}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_OliveGreen_Solid.et"
    }
    SCR_EntityCatalogInventoryItem "{659303CEDE57F487}" {
     m_sEntityPrefab "{A016D4D3B9D40A58}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_4x20_OliveGreen_Solid.et"
    }
    SCR_EntityCatalogInventoryItem "{659303CEDF01451B}" {
     m_sEntityPrefab "{BFF3186D2A9CEFB7}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine_AP2k.et"
    }
    SCR_EntityCatalogInventoryItem "{659303CEDCFF1CCD}" {
     m_sEntityPrefab "{EDE7F2CE157306AD}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_AP2k_OliveGreen_Sand_Stripes.et"
    }
    SCR_EntityCatalogInventoryItem "{659303CEC5C6F0A6}" {
     m_sEntityPrefab "{5D29FA916AB8E593}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_AP2k_OliveGreen_Solid.et"
    }
    SCR_EntityCatalogInventoryItem "{659303CECC84253A}" {
     m_sEntityPrefab "{EF73725A81669E2C}Prefabs/Weapons/Rifles/M16/Rifle_M16A2_carbine_M203.et"
    }
    SCR_EntityCatalogInventoryItem "{659303C9728B26AF}" {
     m_sEntityPrefab "{877128FBE22FF2C9}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_suppressor_AP2K_OliveGreen_Sand_Stripes.et"
    }
    SCR_EntityCatalogInventoryItem "{659303C977BB74AD}" {
     m_sEntityPrefab "{AE81219082244685}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_suppressor_M203_OliveGreen_Sand_Stripes.et"
    }
    SCR_EntityCatalogInventoryItem "{659303C97A7D0E94}" {
     m_sEntityPrefab "{83CE659F2C763F28}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_carbine_suppressor_OliveGreen_Sand_Stripes.et"
    }
    SCR_EntityCatalogInventoryItem "{659303C97EBBC16F}" {
     m_sEntityPrefab "{29DD901C0664FC61}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_suppressor_4x20_OliveGreen_Sand_Stripes.et"
    }
    SCR_EntityCatalogInventoryItem "{659303C9579E0510}" {
     m_sEntityPrefab "{C29B073E2E583220}Prefabs/Weapons/Rifles/M16/Variants/Rifle_M16A2_suppressor_M203_OliveGreen_Sand_Stripes.et"
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6120944188213139}" {
     m_bEnabled 0
    }
   }
  }
 }
}