SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{608E9718DDEA6045}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{66AC788DC730B1E3}" {
     m_sEntityPrefab "{7E06757D25934EBA}Prefabs/Characters/Footwear/ARY_FROCS_01_White.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AC788DC730B178}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66AC788DC0BAB606}" {
     m_sEntityPrefab "{494DB76EE9B7B912}Prefabs/Characters/Footwear/ARY_FROCS_01_Beige.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AC788DC0BA49F9}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66AC788DDDD2A9F4}" {
     m_sEntityPrefab "{6CDFB25B22A381C0}Prefabs/Characters/Footwear/ARY_FROCS_01_Tan.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AC788DDDD2A9A6}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66AC788DD907C996}" {
     m_sEntityPrefab "{E6D595DF462653EC}Prefabs/Characters/Footwear/ARY_FROCS_01_OD.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AC788DD907C945}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66AC788DDA1BB07A}" {
     m_sEntityPrefab "{B6E6778FE0EA0E70}Prefabs/Characters/Footwear/ARY_FROCS_01_Black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AC788DDA1BB035}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66AC788DD7952F68}" {
     m_sEntityPrefab "{B00E800BEF6229D9}Prefabs/Characters/Footwear/ARY_FROCS_01_Green.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AC788DD7952F27}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66AC788DD059CAEB}" {
     m_sEntityPrefab "{64DEF8BC05A802FA}Prefabs/Characters/Footwear/ARY_FROCS_01_Red.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AC788DD059CA5F}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66AC788DEF1CD74E}" {
     m_sEntityPrefab "{38AE992F626382CA}Prefabs/Characters/Footwear/ARY_FROCS_01_Alp.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AC788DEF1CD738}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}