SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD5F13240031}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69784687AE8B8DAB}" {
     m_sEntityPrefab "{D2DC2EF790917302}Prefabs/Characters/HeadGear/Helmet_Altyn/Helmet_Altyn_Black_01.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69784687AE8B8DF8}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 5
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69784687A03FA21C}" {
     m_sEntityPrefab "{BE881A172C55FC2C}Prefabs/Characters/HeadGear/Helmet_Altyn/Helmet_Altyn_Black_02.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69784687A03FA26B}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 5
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69784687A3C5FB5D}" {
     m_sEntityPrefab "{5B1456EE20B06B47}Prefabs/Characters/HeadGear/Helmet_Altyn/Helmet_Altyn_Black_03.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69784687A3C5FA97}" {
       m_eItemType HEADWEAR
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{697B01CCBA28E2B7}" {
     m_sEntityPrefab "{80565556657E0D11}Prefabs/Characters/HeadGear/Helmet_Altyn/Helmet_Altyn_Green_01.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{697B01CCBA28E207}" {
       m_eItemType HEADWEAR
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{697B01CCB5CF14AE}" {
     m_sEntityPrefab "{EC0261B6D9BA823F}Prefabs/Characters/HeadGear/Helmet_Altyn/Helmet_Altyn_Green_02.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{697B01CCB5CF14E7}" {
       m_eItemType HEADWEAR
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{697B01CCB48266B0}" {
     m_sEntityPrefab "{099E2D4FD55F1554}Prefabs/Characters/HeadGear/Helmet_Altyn/Helmet_Altyn_Green_03.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{697B01CCB4826609}" {
       m_eItemType HEADWEAR
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69303096EA62DFE3}" {
     m_sEntityPrefab "{FBCCE53523875FFE}Prefabs/Characters/HeadGear/ShM-62/Mask_Gas_ShM-62_White.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69303096EA62DEB1}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69303096C54EBB37}" {
     m_sEntityPrefab "{C26A13DD20F4E9AD}Prefabs/Characters/HeadGear/ShM-62/Mask_Gas_ShM-62_Black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69303096C54EBA8C}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 1
      }
     }
    }
   }
  }
 }
}