SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{668A96BB2312DED1}" {
   m_sEntityPrefab "{4D4F582F1584821B}Prefabs/Weapons/Magazines/ARY_Magazine_45acp_M3A1_30rnd.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668923E0D6B29E71}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668A96BB2297933A}" {
   m_sEntityPrefab "{D61CF7CA41197110}Prefabs/Weapons/Magazines/ARY_Magazine_45acp_M3A1_30rnd_Mixed.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668A96BB229792E9}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668A96BB3D13CF2A}" {
   m_sEntityPrefab "{3C242A12297EFD77}Prefabs/Weapons/Magazines/ARY_Magazine_45acp_M3A1_30rnd_Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668A96BB3D13CEE1}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
    }
   }
  }
 }
}