SCR_EntityCatalog {
 m_eEntityCatalogType WEAPONS_TRIPOD
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{5C54F92F2439F8B9}" {
   m_sEntityPrefab "{887DB60486A18575}Prefabs/Weapons/Tripods/Tripod_M122_MG_M60.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6056978133FFF65F}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{5C54F92F2465C54E}" {
   m_sEntityPrefab "{73530808E4B455BA}Prefabs/Weapons/Tripods/Tripod_M3_M2HB.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6056978135AB5950}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{6198E4353558CE43}" {
   m_sEntityPrefab "{8094D99689ABE241}Prefabs/Weapons/Mortars/M252/Mortar_M252.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6198E435333AEFD5}" {
    }
   }
  }
 }
}