SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD5F137C9AFF}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{67153D19FC4083D0}" {
     m_sEntityPrefab "{F3DADEF25602BA23}Prefabs/Weapons/Attachments/Optics/ARY_Optic_ZVN64/ARY_Optic_ZVN64_front.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{67153D19FC4083A4}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{67153D19F142EEBE}" {
     m_sEntityPrefab "{9E6B278A7AF0532B}Prefabs/Weapons/Attachments/Optics/ARY_Optic_ZVN64/ARY_Optic_ZVN64_rear.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{67153D19F142EE73}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 1
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6716F875F5F5515C}" {
     m_sEntityPrefab "{92585C6BF4E48E0E}Prefabs/Weapons/Attachments/Optics/ARY_Optic_PU/ARY_Optic_pu.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6716F875F5F5513C}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 20
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6882B7A560C5DD89}" {
     m_sEntityPrefab "{7EB17E874DA8208B}Prefabs/Weapons/Attachments/Optics/Optic_4x20/ARY_Optic_1PN58.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6882B7A560C5D703}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 70
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6882B7A563A8197A}" {
     m_sEntityPrefab "{39ED11CFD21DBBD2}Prefabs/Weapons/Attachments/Optics/Optic_4x20/ARY_Optic_1PN51.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6882B7A563A8192D}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 120
       m_eRequiredRank CAPTAIN
      }
     }
    }
   }
  }
 }
}