SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453CE20F8F}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6638FA8D6F1C0D2E}" {
     m_sEntityPrefab "{C4F22E845D68E559}Prefabs/Weapons/Rifles/ARY_M14/ARY_Rifle_M14_Worn.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6638FA8D6F1C0C8A}" {
       m_eItemMode WEAPON
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{6638FA8D6F1C0C8C}" {
         m_vItemOffset 0 0 -0.12
        }
       }
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66C5336493DD73E9}" {
     m_sEntityPrefab "{5D63AE1BB4CA41EC}Prefabs/Weapons/Rifles/ARY_M14/ARY_Rifle_M14_Worn_OpticMount.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66C5336493DD735B}" {
       m_eItemMode WEAPON
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{66C5336493DD735C}" {
         m_vItemOffset 0 0 -0.12
        }
       }
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C630E4538D3163D}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6638FA8D786A786C}" {
     m_sEntityPrefab "{06C9CA619196C9CC}Prefabs/Weapons/Magazines/ARY_Magazine_762x51_M14_20rnd_Surplus_Ball.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6638FA8D786A7821}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6638FA8D7B26E2C0}" {
     m_sEntityPrefab "{8AD9E1A6E4AB0C35}Prefabs/Weapons/Magazines/ARY_Magazine_762x51_M14_20rnd_Surplus_Last3Tracer.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6638FA8D7B26E28C}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6638FA8D7BB1193F}" {
     m_sEntityPrefab "{3837869937F36307}Prefabs/Weapons/Magazines/ARY_Magazine_762x51_M14_20rnd_Surplus_Tracer.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6638FA8D7BB118EB}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}