SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{69844B93CA7A1F75}" {
   m_sEntityPrefab "{00E0BE909F7BF5B5}Prefabs/Weapons/Core/T33Magazine.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69844B93C74F8912}" {
     m_eItemType PISTOL
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}