SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{69844B931FE1434C}" {
   m_sEntityPrefab "{E535D6527F1D62E5}Prefabs/Weapons/Core/T33.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{69844B931891798F}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_iSupplyCost 0
    }
   }
  }
 }
}