SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "ARMA-RY Attachments"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{66C4E52694E88911}" {
   m_sEntityPrefab "{6D8BB6B6B2BE6E9B}Prefabs/Weapons/Attachments/Optics/ARY_Optic_APElectronic_Dovetail/ARY_Collim_APElectronic_Dovetail.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C4E526F74B3A30}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 9
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66C4E526978E7E73}" {
   m_sEntityPrefab "{56E19D0DA7532B1D}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C4E5268AD91B56}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 12
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66C4E526965D4375}" {
   m_sEntityPrefab "{15CFEB9E0DBD9B86}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k_Silver.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C4E52688345BA6}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 12
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66C74B76427B284C}" {
   m_sEntityPrefab "{9A17E9F224E302A6}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k_OD.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C74B76427B2EC0}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 13
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66C74B7659BBC788}" {
   m_sEntityPrefab "{16755AC216F2904E}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k_Sand.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C74B7659BBC743}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 13
     m_eRequiredRank LIEUTENANT
    }
   }
  }
 }
}