SCR_EntityCatalog {
 m_eEntityCatalogType WEAPONS_TRIPOD
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{646F2814540DBDA5}" {
   m_sEntityPrefab "{D7D67566D0A78E0A}Prefabs/Weapons/Mortars/L16/Mortar_L16.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{646F2814540DBDA6}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{647D375057D12EC2}" {
   m_sEntityPrefab "{19B8FEA4D767B3C7}Prefabs/Weapons/Tripods/Monopod_LouchPole_GPMG.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{647D375057D12ECF}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{648740965055974D}" {
   m_sEntityPrefab "{93D05BC98A15A0EF}Prefabs/Weapons/Tripods/Tripod_GPMG.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6487409650559700}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{647D375057D12ED6}" {
   m_sEntityPrefab "{AA35709DD4F778B6}Prefabs/Weapons/Tripods/Tripod_M3_M2HB_UK.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{647D375057D15F6D}" {
    }
   }
  }
 }
}