SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{64A95E6A30EF620C}" {
     m_sEntityPrefab "{A5C93DE27C0AF521}Prefabs/Weapons/Handguns/M93R/Handgun_M93R.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{64A95E6A30EC9DBD}" {
       m_eItemType PISTOL
       m_eItemMode WEAPON
       m_iSupplyCost 7
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{64A95E6A30EC9DB3}" {
        }
       }
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{651738BA837FB8C7}" {
     m_sEntityPrefab "{61EF158A840B556E}Prefabs/Weapons/Handguns/M93R/Handgun_M93R_Prototype.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{651738BA837FB96E}" {
       m_eItemType PISTOL
       m_eItemMode WEAPON
       m_iSupplyCost 11
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{651738BA837FB961}" {
        }
       }
       m_eRequiredRank LIEUTENANT
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA6FA1B8}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{64A95E6A2DF77123}" {
     m_sEntityPrefab "{12E78927A1365B03}Prefabs/Weapons/Magazines/Magazine_9x19_M93R_60rnd_drum_Ball_Ext.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{64A95E6A2DF77167}" {
       m_eItemType PISTOL
       m_eItemMode AMMUNITION
       m_iSupplyCost 6
       m_eRequiredRank CAPTAIN
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{64A95E6A2FDE74A2}" {
     m_sEntityPrefab "{DA83F6E3CA0F486C}Prefabs/Weapons/Magazines/Magazine_9x19_M93R_20rnd_Ball_Ext.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{64A95E6A2FDE74F1}" {
       m_eItemType PISTOL
       m_eItemMode AMMUNITION
       m_iSupplyCost 2
       m_eRequiredRank CORPORAL
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA315A22}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{651738BB7A567C70}" {
     m_sEntityPrefab "{598749168D4B01F1}Prefabs/Weapons/Attachments/Stocks/Stock_M93R/Stock_M93R_base.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{651738BB7A567C01}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 4
       m_eRequiredRank SERGEANT
      }
     }
    }
   }
  }
 }
}