SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453CE20F8F}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{668AFC7A015F898D}" {
     m_sEntityPrefab "{6DE8D9757C3E417E}Prefabs/Weapons/Rifles/ARY_M3A1/ARY_Rifle_M3A1_Worn.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{668AFC7A015F8908}" {
       m_eItemMode WEAPON
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{668AFC7A015F890A}" {
         m_vItemOffset 0 0 -0.12
        }
       }
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C630E4538D3163D}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{668AFC7A1F9DD4EA}" {
     m_sEntityPrefab "{4D4F582F1584821B}Prefabs/Weapons/Magazines/ARY_Magazine_45acp_M3A1_30rnd.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{668AFC7A1F9DD4A3}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}