SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{663934CEDFA2565B}" {
   m_sEntityPrefab "{15F0CB459CE8750E}Prefabs/Weapons/Rifles/ARY_M16_US/ARY_Rifle_M16A1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66393382EA274594}" {
     m_eItemMode WEAPON
     m_iSupplyCost 8
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66393382EA274588}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66C750A565FA8F21}" {
   m_sEntityPrefab "{429865BEFCABA7D7}Prefabs/Weapons/Rifles/ARY_M16_US/ARY_Rifle_M16A1_Optic.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C750A55CFBBECD}" {
     m_eItemMode WEAPON
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66C750A55CFBBECF}" {
       m_vItemOffset 0 0 -0.2
      }
     }
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663934CEDE62D627}" {
   m_sEntityPrefab "{B558A40137A3BB4C}Prefabs/Weapons/Rifles/ARY_M16_US/ARY_Rifle_M16A1_M203.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663933F8C258C19F}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 8
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{663933F8C258C191}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663934CED9182249}" {
   m_sEntityPrefab "{EBE0251FAE2C03A0}Prefabs/Weapons/Rifles/ARY_M16_US/ARY_Rifle_XM177E2.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663933F8C31DE3A9}" {
     m_eItemMode WEAPON
     m_iSupplyCost 12
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66432992960618CB}" {
       m_vItemOffset 0 0 -0.2
      }
     }
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66C750A560AEF750}" {
   m_sEntityPrefab "{1995417A639FD79D}Prefabs/Weapons/Rifles/ARY_M16_US/ARY_Rifle_XM177E2_Optic.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C750A555FBA917}" {
     m_eItemMode WEAPON
     m_iSupplyCost 14
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663D30042924F92F}" {
   m_sEntityPrefab "{AA89E7DF69A3CF6C}Prefabs/Weapons/Rifles/ARY_M16_US/Worn/ARY_Rifle_M16A1_Worn.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663D30042924F965}" {
     m_eItemMode WEAPON
     m_iSupplyCost 8
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{663D30042924F960}" {
       m_vItemOffset 0 0 -0.2
      }
     }
    }
   }
  }
 }
}