SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{666B1D8BA045CB0C}" {
   m_sEntityPrefab "{720FF9D713E63C65}Prefabs/Weapons/Rifles/AK74/ARY_Rifle_AK74_Polymer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666ADD0AA3B78F05}" {
     m_eItemMode WEAPON
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{666ADD0AA3B78F07}" {
       m_vItemOffset 0 0 -0.2
      }
     }
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8BBE0D3E17}" {
   m_sEntityPrefab "{C131C70590E38E25}Prefabs/Weapons/Rifles/AK74/ARY_Rifle_AK74N_Polymer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666AF7940E4FBA6E}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 25
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668ED21DEEA510F5}" {
   m_sEntityPrefab "{FF9B3B4365022C24}Prefabs/Weapons/Rifles/AK74/Variants - Plum/ARY_Rifle_AK74N_GP25_Polymer_Plum.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668ED21DEEA51041}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 25
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8BBEEA1442}" {
   m_sEntityPrefab "{737CBCC26C2083D8}Prefabs/Weapons/Rifles/AK74/ARY_Rifle_AK74_Polymer_Green.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666ADD0AA2FCEE87}" {
     m_eItemMode WEAPON
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{666ADD0AA2FCEEB9}" {
       m_vItemOffset 0 0 -0.2
      }
     }
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8BB97814DE}" {
   m_sEntityPrefab "{2CE730629D8AD46C}Prefabs/Weapons/Rifles/AK74/ARY_Rifle_AK74N_Polymer_Green.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666AF7941843C5E1}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 25
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8BB8358050}" {
   m_sEntityPrefab "{75944B4663A8A471}Prefabs/Weapons/Rifles/AK74/ARY_Rifle_AK74_Polymer_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666ADD0AA26646C5}" {
     m_eItemMode WEAPON
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{666ADD0AA26646C7}" {
       m_vItemOffset 0 0 -0.2
      }
     }
     m_eRequiredRank MAJOR
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8BB8C82200}" {
   m_sEntityPrefab "{2A0FC7E69202F3C5}Prefabs/Weapons/Rifles/AK74/ARY_Rifle_AK74N_Polymer_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666AF79411790F02}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 25
     m_eRequiredRank MAJOR
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668ED21DE7F9506E}" {
   m_sEntityPrefab "{34C3A913DFC4A730}Prefabs/Weapons/Rifles/AK74/Variants - Black/ARY_Rifle_AK74N_GP25_Polymer_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668ED21DE7F953D0}" {
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 25
     m_eRequiredRank MAJOR
    }
   }
  }
 }
}