SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{666B1D8B4048562D}" {
   m_sEntityPrefab "{2C5AE1171BF060F1}Prefabs/Weapons/Magazines/ARY_Magazine_545x39_AK_30rnd_Ball_Plum.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666ADD04DC1ADB88}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8B40E713F3}" {
   m_sEntityPrefab "{B416017C5C7F3EE2}Prefabs/Weapons/Magazines/ARY_Magazine_545x39_AK_30rnd_Last_5Tracer_Plum.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666ADD04DCBB4735}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8B43A5B310}" {
   m_sEntityPrefab "{61F5D9F0101A5629}Prefabs/Weapons/Magazines/ARY_Magazine_545x39_AK_30rnd_Tracer_Plum.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666ADD04DF6D160E}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8B4211AF2A}" {
   m_sEntityPrefab "{897AC6A88EB5669E}Prefabs/Weapons/Magazines/ARY_Magazine_545x39_AK_30rnd_Ball_Green.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666ADD07C0D7C610}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8B4279F42F}" {
   m_sEntityPrefab "{4CF15FDB2DF183F6}Prefabs/Weapons/Magazines/ARY_Magazine_545x39_AK_30rnd_Last_5Tracer_Green.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666ADD07C03BF184}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8B42E28690}" {
   m_sEntityPrefab "{2A0440F65D15D0C3}Prefabs/Weapons/Magazines/ARY_Magazine_545x39_AK_30rnd_Tracer_Green.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666ADD07C1A3C302}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank CAPTAIN
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8B5D4A42B7}" {
   m_sEntityPrefab "{62A4A1AE8957F887}Prefabs/Weapons/Magazines/ARY_Magazine_545x39_AK_30rnd_Ball_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666AF795C1BC9B84}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank MAJOR
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8B5DC7FAF1}" {
   m_sEntityPrefab "{CE01B276FD441F29}Prefabs/Weapons/Magazines/ARY_Magazine_545x39_AK_30rnd_Last_5Tracer_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666AF795C6FBB82D}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank MAJOR
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{666B1D8B5C762C11}" {
   m_sEntityPrefab "{E1B3C97E8F2E8121}Prefabs/Weapons/Magazines/ARY_Magazine_545x39_AK_30rnd_Tracer_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{666AF795C6520298}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank MAJOR
    }
   }
  }
 }
}