SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{665B3C0B8AC3E948}" {
   m_sEntityPrefab "{763ECB7A13E6E4AD}Prefabs/Characters/Factions/BLUFOR/US_Army/ARY_Character_US_Officer_1911.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{665B3C0B8AC3E938}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{665B3C0B8AC3E93B}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}