SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{669110F14E27150C}" {
   m_sEntityPrefab "{E6B86CCD5B335074}Prefabs/Characters/Factions/BLUFOR/US_Army/GreenBerets/Suppressed/ARY_Character_US_SF_S_UZI.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{669110F14E2714ED}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{669110F14E2714EF}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}