SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{69F8F1F8D816C4A9}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69F8F1F8D816C497}" {
     m_sEntityPrefab "{26223738A07F8203}Prefabs/LCJ/Backpack_GunBag_Black_LCJ.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69F8F1F8D816C496}" {
       m_eItemType BACKPACK
       m_iSupplyCost 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{69F8F1F8D816C493}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{69F8F1F8D816C492}" {
     m_sEntityPrefab "{715AE241C2E4BB12}Prefabs/LCJ/ARY_FROCS_01_Tan_LCJ.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69F8F1F8D816C49D}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}