SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA315A22}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{660F416BD97502C5}" {
     m_sEntityPrefab "{DB14946F5472DA61}Prefabs/Weapons/Attachments/Optics/ARY_Optic_APElectronic/ARY_Collim_APElectronic.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{606084A3AC514F5E}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6606BD0F225EADD6}" {
     m_sEntityPrefab "{A78EF315BE900C23}Prefabs/Weapons/Attachments/Optics/ARY_Optic_ZF4/ARY_Optic_Z24_4x.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C62F7D8680EBEA9}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 32
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6606BD0F3435FF67}" {
     m_sEntityPrefab "{03E8553297A72CCA}Prefabs/Weapons/Attachments/Optics/ARY_Optic_SG1/ARY_Optic_G3_DA_1-5_6x.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C62F7D86AED1F20}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 75
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{661F37E2C658CB84}" {
     m_sEntityPrefab "{B8A2547514B6F9FF}Prefabs/Weapons/Attachments/Optics/ARY_Optic_Flashlight_ClawMount/ARY_Flashlight_Clawmount.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{661F37E2C658CE14}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_eRequiredRank SERGEANT
      }
     }
    }
   }
  }
 }
}