SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453B27FB86}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{690AB2F74EF331A3}" {
     m_sEntityPrefab "{CA664EB10FEF61C0}Prefabs/Characters/Uniforms/Jacket_Bandit/Jacket_Bandit_brown.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{690AB2F74EF3315F}" {
       m_eItemType TORSO
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{690AB2F74F4A2960}" {
     m_sEntityPrefab "{05F79694F3C2E8A3}Prefabs/Characters/Uniforms/Jacket_Bandit/Jacket_Bandit_white.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{690AB2F74F4A291D}" {
       m_eItemType TORSO
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}