SCR_EntityCatalogMultiList {
 m_eEntityCatalogType ITEM
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{62D7410A9D46207E}" : "{C2EE8603146E36CB}Configs/EntityCatalog/UK/Arsenal Lists/UK_Weapons_All.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{62D741081C4FB8F8}" : "{9B8732534F2FCDAE}Configs/EntityCatalog/UK/Arsenal Lists/UK_Ammunition_All.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{62DD3B297752B585}" : "{37FBA7E7466F4CB9}Configs/EntityCatalog/UK/Arsenal Lists/UK_WeaponAttachments_All.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{62DD3B29765366B7}" : "{0F0D0C941E412EE7}Configs/EntityCatalog/UK/Arsenal Lists/UK_Explosives_All.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{62DD3B2896AEA994}" : "{92B601BD2DC5A55F}Configs/EntityCatalog/UK/Arsenal Lists/UK_Equipment_All.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{62DD3B2FD8779B17}" : "{89C89802F8B15EF0}Configs/EntityCatalog/UK/Arsenal Lists/UK_BackpacksVests_All.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{62DD3B2EC3530C21}" : "{2A937B904F3FA670}Configs/EntityCatalog/UK/Arsenal Lists/UK_Clothing_All.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{633B0177EEAB95F5}" : "{46253DA2AA55659A}Configs/EntityCatalog/UK/Arsenal Lists/UK_Others_All.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{6676DAB944E2B29C}" : "{6326285D4F4B3A2D}Configs/EntityCatalog/UK/Arsenal Lists/UK_Deployables_All.conf" {
  }
  SCR_EntityCatalogMultiListEntry "{66BAF044DADFEEBB}" : "{29468CBA5D676056}Configs/EntityCatalog/UK/Arsenal Lists/UK_WeaponAttachments_Hidden.conf" {
  }
 }
}