SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697826E2AC672}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{673444A59B6E975C}" {
     m_sEntityPrefab "{9B9DF3CDAFDF6BE3}Prefabs/Vehicles/Wheeled/UAZ452/UAZ452_transport_Bandit.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{673444A59B6E9697}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{67354C5622FEAD60}" {
     m_sEntityPrefab "{A7E5B1A06532EA8A}Prefabs/Vehicles/Wheeled/UAZ452/UAZ452_Armed_Bandit.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{67354C5622FEACCE}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{673444A5EEFE7963}" {
     m_sEntityPrefab "{DC08B2446B718430}Prefabs/Vehicles/Wheeled/S105/S105_Bandit.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{673444A5EEFE78AD}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{673444A5E5037284}" {
     m_sEntityPrefab "{BB74B5B15F8A091B}Prefabs/Vehicles/Wheeled/S105/S105_Bandit_02.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{673444A5E50372C1}" {
      }
     }
    }
   }
  }
 }
}