SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{69F350181CC56C70}" {
   m_sEntityPrefab "{7E5ECFF1F8492982}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Unarmed.et"
  }
  SCR_EntityCatalogEntry "{69F3501837E0B04F}" {
   m_sEntityPrefab "{62CCD1B663BBBEC3}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Recruit_BoltAction.et"
  }
  SCR_EntityCatalogEntry "{69F3501823C71F9E}" {
   m_sEntityPrefab "{14F83B2BE7EFD43A}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Recruit_Handgun.et"
  }
  SCR_EntityCatalogEntry "{69F35018246E69DA}" {
   m_sEntityPrefab "{870D87CA0105EF81}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Recruit_Shotgun.et"
  }
  SCR_EntityCatalogEntry "{69F35018EB27291A}" {
   m_sEntityPrefab "{435830A3964E0573}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Militiaman_AT.et"
  }
  SCR_EntityCatalogEntry "{69F35018E91E538B}" {
   m_sEntityPrefab "{AD9AE8F8AE1B1348}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Militiaman_Crewman.et"
  }
  SCR_EntityCatalogEntry "{69F35018E9F2FD7C}" {
   m_sEntityPrefab "{6D167785C292F62A}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Militiaman_Grenadier.et"
  }
  SCR_EntityCatalogEntry "{69F35018EF3CEC93}" {
   m_sEntityPrefab "{C9EB3AE9FA25DE58}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Militiaman_Medic.et"
  }
  SCR_EntityCatalogEntry "{69F35018EFEE3BF9}" {
   m_sEntityPrefab "{C9E7877881880FCC}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Militiaman_MG.et"
  }
  SCR_EntityCatalogEntry "{69F35018EEC05FCC}" {
   m_sEntityPrefab "{F8EB0B9DA82E4F8F}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Militiaman_Shotgun.et"
  }
  SCR_EntityCatalogEntry "{69F35018EDED122A}" {
   m_sEntityPrefab "{F678A87DDD43B93C}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Militiaman_SL.et"
  }
  SCR_EntityCatalogEntry "{69F350189C10AABC}" {
   m_sEntityPrefab "{01132AACE86553EA}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_AT.et"
  }
  SCR_EntityCatalogEntry "{69F350189CFD0B09}" {
   m_sEntityPrefab "{F0CEF7A1C3D91CD1}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_Crewman.et"
  }
  SCR_EntityCatalogEntry "{69F35018826C5731}" {
   m_sEntityPrefab "{C43F7123B719D476}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_Grenadier.et"
  }
  SCR_EntityCatalogEntry "{69F35018810C344A}" {
   m_sEntityPrefab "{F72B01847B1FE1F6}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_LAT.et"
  }
  SCR_EntityCatalogEntry "{69F35018877C4B8A}" {
   m_sEntityPrefab "{017B6C58221008C6}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_Medic.et"
  }
  SCR_EntityCatalogEntry "{69F35018864144A8}" {
   m_sEntityPrefab "{8BAC9D77FFA35955}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_MG.et"
  }
  SCR_EntityCatalogEntry "{69F3501885262D90}" {
   m_sEntityPrefab "{F27B3CB7627E6D13}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_Officer.et"
  }
  SCR_EntityCatalogEntry "{69F3501880AD9F55}" {
   m_sEntityPrefab "{47F7F29C1B73E4D4}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_Pilot.et"
  }
  SCR_EntityCatalogEntry "{69F3501881A830D2}" {
   m_sEntityPrefab "{641FCBA4C73FA379}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_Rifle.et"
  }
  SCR_EntityCatalogEntry "{69F35018B8DC2874}" {
   m_sEntityPrefab "{831A55CAACE30E52}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_Sapper.et"
  }
  SCR_EntityCatalogEntry "{69F35018BF63B4ED}" {
   m_sEntityPrefab "{FBC503054700CEEE}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_Scout.et"
  }
  SCR_EntityCatalogEntry "{69F35018BE7E2B32}" {
   m_sEntityPrefab "{B433B272A368EFA5}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_SL.et"
  }
  SCR_EntityCatalogEntry "{69F35018BDBEBD9C}" {
   m_sEntityPrefab "{ED97CDAB9BCC41B8}Prefabs/Characters/Factions/INDFOR/CLA/Character_CLA_Veteran_Sniper.et"
  }
 }
}