SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{663934CEE624E97E}" {
   m_sEntityPrefab "{7C184B75459B4831}Prefabs/Weapons/Attachments/Bayonets/ARY_Bayonet_M7.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663933F8FB64A870}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663934CEE6C238D2}" {
   m_sEntityPrefab "{69B9FDF0F3A65850}Prefabs/Weapons/Attachments/Muzzle/ARY_FlashHiders_AR15/ARY_FlashHider_M16_DuckBill.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663933F8F1769BAD}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663934CEE00F3E4D}" {
   m_sEntityPrefab "{978EFB9B82024BDF}Prefabs/Weapons/Attachments/Muzzle/ARY_FlashHiders_AR15/ARY_FlashHider_M16_ThreeProng.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663933F8F084A0FA}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663934CEE3304CB2}" {
   m_sEntityPrefab "{6EEF76C04C04FDA7}Prefabs/Weapons/Attachments/Muzzle/ARY_FlashHiders_AR15/ARY_FlashHider_M16_BirdCage.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{663933F8F3108B2B}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
    }
   }
  }
 }
}