SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6A02F9AAE3AB86DB}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6A02F9AAE3AB86C1}" {
     m_sEntityPrefab "{26223738A07F8203}Prefabs/LCJ/Backpack_GunBag_Black_LCJ.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A02F9AAE3AB86C3}" {
       m_eItemType BACKPACK
       m_iSupplyCost 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6A02F9AAE3AB86CD}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6A02F9AAE3AB86CE}" {
     m_sEntityPrefab "{715AE241C2E4BB12}Prefabs/LCJ/ARY_FROCS_01_Tan_LCJ.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6A02F9AAE3AB86CF}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}