SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453CE20F8F}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{67132184C01C69A9}" {
     m_sEntityPrefab "{78AB14214ED62F38}Prefabs/Weapons/Rifles/ARY_AKM/ARY_Rifle_AK_47.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{67132184C01C6165}" {
       m_eItemMode WEAPON
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{67132184C01C6167}" {
         m_vItemOffset 0 0 -0.12
        }
       }
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{67132184DBC63426}" {
     m_sEntityPrefab "{8F0807ABED77AEDE}Prefabs/Weapons/Rifles/ARY_AKM/ARY_Rifle_AKM_scav.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{67132184DBC6378C}" {
       m_eItemMode WEAPON
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{67132184DBC6378E}" {
         m_vItemOffset 0 0 -0.12
        }
       }
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{671EA176DB490A6F}" {
     m_sEntityPrefab "{6A7FF4C51334EA4D}Prefabs/Weapons/Rifles/ARY_AKM/ARY_Rifle_RPK.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66A6C1F0F868E33B}" {
       m_eItemType MACHINE_GUN
       m_eItemMode WEAPON
       m_iSupplyCost 15
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{66A6C1F0F868E33D}" {
         m_vItemOffset 0 0 -0.2
        }
       }
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C630E4538D3163D}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{67132184EDE53395}" {
     m_sEntityPrefab "{2612E1A7DD2F4DFE}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_30rnd_Ball.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{67132184EDE53379}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{67132184E5748850}" {
     m_sEntityPrefab "{B11727710EC12776}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_30rnd_Last_5Tracer.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{67132184E5748802}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{67132184E6CDEBEC}" {
     m_sEntityPrefab "{811F098714578F82}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_30rnd_Tracer.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{67132184E6CDEB58}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{671EA176D7B98F33}" {
     m_sEntityPrefab "{B74501AFC4A93758}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_40rnd_Steel_Ball.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66CF509449DA4998}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 2
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{671EA176D6F7D353}" {
     m_sEntityPrefab "{FA95A7DF7048AB33}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_40rnd_Steel_4B1TMix.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66CF50944416DEE1}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 2
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{671EA176D1CEF25B}" {
     m_sEntityPrefab "{AB52A62B8DAC9003}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_40rnd_Steel_Tracer.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66CF509441094E11}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 2
       m_eRequiredRank CORPORAL
      }
     }
    }
   }
  }
 }
}