SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{693030972DC8D48F}" {
     m_sEntityPrefab "{B74A4FF0DD8BB116}Prefabs/Characters/HeadGear/Helmet_PASGT_01/Helmet_PASGT_01.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{693030972DC8D4D8}" {
       m_eItemType HEADWEAR
       m_iSupplyCost 2
       m_eRequiredRank SERGEANT
      }
     }
    }
   }
  }
 }
}