SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{695175E3E3D589CA}" {
   m_sIdentifier "NORTHCOM: AUG-A1"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{695175E3DB12F339}" {
     m_sEntityPrefab "{85E4D7914F54AC1E}Prefabs/Weapons/Rifles/AUG/Rifle_AUGA1_STG77.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{695175E3D8B608A6}" {
       m_eItemMode WEAPON
       m_iSupplyCost 15
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{695802A8654F9D2F}" {
     m_sEntityPrefab "{27C295211CBD428B}Prefabs/Weapons/Rifles/AUG/Rifle_AUGA1_STG77_SD.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{695802A8654F9C99}" {
       m_eItemMode WEAPON
       m_iSupplyCost 15
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{695175E3D790C331}" {
     m_sEntityPrefab "{A87451CC0930F228}Prefabs/Weapons/Attachments/Suppressor/Suppressor_T4AUG.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{695175E3D790C3A4}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{695175E3CA0E92F7}" {
     m_sEntityPrefab "{384BFA7519CFA091}Prefabs/Weapons/Magazines/Magazine_556x45_Waffle_M995_MODERNAMMO.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{695175E3CA0E928F}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{695175E3C138C8A3}" {
     m_sEntityPrefab "{21F5EFBA17F3DFFE}Prefabs/Weapons/Magazines/Magazine_556x45_Waffle_M855_1980sAMMO.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{695175E3C138CB73}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}