SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{665B3E736DAEEE5E}" {
   m_sEntityPrefab "{2D96BB5F754FD954}Prefabs/Weapons/Handguns/ARY_1911/ARY_Handgun_1911_delta.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{665B3E736DAEE1C4}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{665B3E736DAEE1C5}" {
      }
     }
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{665D3065C1F25973}" {
   m_sEntityPrefab "{3F6CA85A6D4AE898}Prefabs/Weapons/Handguns/ARY_1911/ARY_Handgun_1911_delta_od.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{665D3065C1F2592E}" {
     m_eItemType PISTOL
     m_eItemMode WEAPON
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{665D3065C1F25920}" {
      }
     }
     m_eRequiredRank LIEUTENANT
    }
   }
  }
 }
}