SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{66130A0D3F4E4762}" {
   m_sEntityPrefab "{EAE3502AD7C222E1}Prefabs/Weapons/Attachments/Optics/ARY_Optic_PSG1/ARY_Optic_PSG1_ZF_6x42.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{660B2E9742EDC39E}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 75
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66213415096F508E}" {
   m_sEntityPrefab "{F04253AA8993B906}Prefabs/Weapons/Attachments/Muzzle/ARY_Suppressor_G3/ARY_Suppressor_G3.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{662134156619F880}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 15
     m_eRequiredRank SERGEANT
    }
   }
  }
 }
}