SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{6638FA8DB770AB8A}" {
   m_sEntityPrefab "{C2F3BCE6394C1756}Prefabs/Weapons/Magazines/ARY_Magazine_762x51_M14_20rnd_M80_M62_Last3Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6638FA8DA06E63F2}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{664E98C038EAD53A}" {
   m_sEntityPrefab "{06C9CA619196C9CC}Prefabs/Weapons/Magazines/ARY_Magazine_762x51_M14_20rnd_Surplus_Ball.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6638FA8D786A7821}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{664E98C03B83D944}" {
   m_sEntityPrefab "{8AD9E1A6E4AB0C35}Prefabs/Weapons/Magazines/ARY_Magazine_762x51_M14_20rnd_Surplus_Last3Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6638FA8D7B26E28C}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{664E98C03A3269C6}" {
   m_sEntityPrefab "{3837869937F36307}Prefabs/Weapons/Magazines/ARY_Magazine_762x51_M14_20rnd_Surplus_Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6638FA8D7BB118EB}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 0
    }
   }
  }
 }
}