SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{668A96BB383D1662}" {
   m_sEntityPrefab "{FEC8CBDEE23E76D3}Prefabs/Weapons/Attachments/Muzzle/ARY_FlashHider_M3A1/ARY_FlashHider_M3A1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66873087A5DCF16A}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 1
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668A96BB3419B7B3}" {
   m_sEntityPrefab "{B791D3DA614D31E3}Prefabs/Weapons/Attachments/Muzzle/ARY_FlashHider_M3A1/ARY_FlashHider_M3A1_SL20.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668A96BB3419B776}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 1
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668A96BB349F9524}" {
   m_sEntityPrefab "{580B584A5DD76B7D}Prefabs/Weapons/Attachments/Muzzle/ARY_Suppressor_M3A1/ARY_Suppressor_M3A1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668A96BB349F9498}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 1
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{668A96BB37190C66}" {
   m_sEntityPrefab "{DED1D013F524EE69}Prefabs/Weapons/Attachments/Muzzle/ARY_Suppressor_M3A1/ARY_Suppressor_M3A1_SL20.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{668A96BB37190FD7}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 1
     m_eRequiredRank SERGEANT
    }
   }
  }
 }
}