SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Others - All (British Forces)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{633B0177CE948E19}" {
   m_sEntityPrefab "{AF6ECB8928E020C3}Prefabs/Items/PersonalBelongings/PersonalBelongings_UK.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{633B0177CE948E1E}" {
     m_eItemType HEADWEAR
     m_iSupplyCost 1
    }
    SCR_ArsenalItem "{6134C332014C4503}" {
     m_eItemType EQUIPMENT
     m_iSupplyCost 0
    }
    SCR_EntityCatalogIdentityItemData "{621AA6320CDE28E9}" {
    }
   }
  }
 }
}