SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Attachments (Not in arsenal for cost calulation)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{66BAF045108CEF63}" {
   m_sEntityPrefab "{CCDD534EECACA632}Prefabs/Weapons/Attachments/Underbarrel/LAW80_SpottingRifle_Base.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{60E8BC7106A8222F}" {
     m_iSupplyCost 1
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66BAF04529035F59}" {
   m_sEntityPrefab "{A15A8F219731759A}Prefabs/Weapons/Ammo/Ammo_LAW80_Spotting_Tracer.et"
   m_aEntityDataList {
    SCR_NonArsenalItemCostCatalogData "{66BAF04529035F0F}" {
     m_iSupplyCost 1
    }
   }
  }
 }
}