SCR_Faction : "{3FA20B01D950D31E}Configs/Factions/Non-Combatant.conf" {
 FactionKey "DL_CIV"
 UIInfo SCR_FactionUIInfo "{56B49118D8D0A9C5}" {
  Name "Dynamic Loot Civilians"
  Description "Faction which onyl purpose is to offer extra civilian Loot for Dynamic Loot while preventing civilian NPC to spawn with  extra loot."
  Icon "{7BB7AE674BE729CE}UI/Textures/Editor/EditableEntities/Factions/EditableEntity_Faction_CIV.edds"
  m_sNameUpper "DYNAMIC LOOT CIVILIANS"
 }
 m_FactionLabel FACTION_CIV
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{69F50C946FEC2220}" : "{180DE11945D4ABBB}Configs/EntityCatalog/CIV_DL/InventoryItems_EntityCatalog_CIV_for_CIV_DL.conf" {
  }
  SCR_EntityCatalogMultiList "{69F50C946D7DA072}" : "{29F0A08191F5E067}Configs/EntityCatalog/CIV_DL/InventoryItems_EntityCatalog_FIA_for_CIV_DL.conf" {
  }
  SCR_EntityCatalogMultiList "{69F50C946B69B129}" : "{CA123BFD2D1D53EB}Configs/EntityCatalog/CIV_DL/InventoryItems_EntityCatalog_USSR_for_CIV_DL.conf" {
  }
 }
}