SCR_Faction : "{3FA20B01D950D31E}Configs/Factions/Non-Combatant.conf" {
 FactionKey "DL_CIV"
 FactionColor 0.1376 0.0578 0.2141 1
 UIInfo SCR_FactionUIInfo "{56B49118D8D0A9C5}" {
  Name "Dynamic Loot Civilians"
  Description "Faction which onyl purpose is to offer extra civilian Loot for Dynamic Loot while preventing civilian NPC to spawn with  extra loot."
  Icon "{7BB7AE674BE729CE}UI/Textures/Editor/EditableEntities/Factions/EditableEntity_Faction_CIV.edds"
  m_sNameUpper "DYNAMIC LOOT CIVILIANS"
 }
 "Radio encryption key" "Sandbox"
 m_OutlineFactionColor 0.019 0 0.033 1
 m_NotificationFactionColor 0.203 0.083 0.319 1
 m_NotificationTextFactionColor 0.138 0.058 0.214 1
 m_bIsCommanderAvailable 0
 m_bCanCaptureBases 0
 m_bTasksEnabled 0
 m_FactionLabel FACTION_CIV
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{69F281721F68DD3A}" : "{25108C676D42B984}Configs/EntityCatalog/DL_CIV/InventoryItems_EntityCatalog_DL_CIV.conf" {
  }
 }
}