SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{665B1AF486DCE624}" {
   m_sEntityPrefab "{81563D558B5BCF69}Prefabs/Weapons/Magazines/ARY_Magazine_45acp_1911_7rnd.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{661A9DB35C41C341}" {
     m_eItemType PISTOL
     m_eItemMode AMMUNITION
     m_iSupplyCost 1
     m_eRequiredRank SERGEANT
    }
   }
  }
 }
}