SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{66C74B77EBD0A427}" {
     m_sEntityPrefab "{4920900437268669}Prefabs/Weapons/Rifles/M16/ARY_Rifle_M16A2_Rail.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66C74B77EBD0A7BB}" {
       m_eItemMode WEAPON
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{66C74B77EBD0A7BF}" {
         m_vItemOffset 0 0 -0.2
        }
       }
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66C74B7741AF75F5}" {
     m_sEntityPrefab "{6CA652FDA16DAF89}Prefabs/Weapons/Rifles/M16/ARY_Rifle_M16A2_carbine_Rail.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66C74B7741AF75A5}" {
       m_eItemMode WEAPON
       m_iSupplyCost 14
       m_eRequiredRank SERGEANT
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA315A22}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{66C4E526F74B3AD2}" {
     m_sEntityPrefab "{6D8BB6B6B2BE6E9B}Prefabs/Weapons/Attachments/Optics/ARY_Optic_APElectronic_Dovetail/ARY_Collim_APElectronic_Dovetail.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66C4E526F74B3A30}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 9
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66C4E5268AD91B0B}" {
     m_sEntityPrefab "{56E19D0DA7532B1D}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66C4E5268AD91B56}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 12
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66C4E52688345C5A}" {
     m_sEntityPrefab "{15CFEB9E0DBD9B86}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k_Silver.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66C4E52688345BA6}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 12
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66C74B7656F8B019}" {
     m_sEntityPrefab "{9A17E9F224E302A6}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k_OD.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66C74B76427B2EC0}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 13
       m_eRequiredRank LIEUTENANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66C74B766C121E3A}" {
     m_sEntityPrefab "{16755AC216F2904E}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k_Sand.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66C74B7659BBC743}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 13
       m_eRequiredRank LIEUTENANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6882B0DB73DD8F1A}" {
     m_sEntityPrefab "{BE1CFA9938D482C5}Prefabs/Weapons/Attachments/Optics/ARY_Optic_ANPVS2/ARY_Optic_ANPVS2_M16Mount.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6642A460F728A340}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 80
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{6882B0DB727D80FC}" {
     m_sEntityPrefab "{664BC1124312DF2D}Prefabs/Weapons/Attachments/Optics/ARY_Optic_ANPVS4/ARY_Optic_ANPVS4_M16Mount.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66F741DA6193077C}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 100
       m_eRequiredRank LIEUTENANT
      }
     }
    }
   }
  }
 }
}