SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E4538D3163D}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{685512FA5C5E5145}" {
     m_sEntityPrefab "{843D9B182BCD2765}Prefabs/Weapons/Magazines/NSV/Box_127x108_NSV_50rnd_4AP_1APIT.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{685512FA5C5E6E74}" {
       m_eItemType MACHINE_GUN
       m_eItemMode AMMUNITION
       m_iSupplyCost 5
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{685512FA401BA32B}" {
     m_sEntityPrefab "{7DD9CA7DE97AB9C0}Prefabs/Weapons/Magazines/NSV/Box_127x108_NSV_50rnd_API.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{685512FA401BA032}" {
       m_eItemType MACHINE_GUN
       m_eItemMode AMMUNITION
       m_iSupplyCost 5
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{685512FA45E161DD}" {
     m_sEntityPrefab "{4CD3159446EC131B}Prefabs/Weapons/Magazines/NSV/Box_127x108_NSV_50rnd_APIT.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{685512FA45E17ED7}" {
       m_eItemType MACHINE_GUN
       m_eItemMode AMMUNITION
       m_iSupplyCost 5
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C630E453B27FB86}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5C62F7DFB2CD733A}" {
     m_bEnabled 0
    }
    SCR_EntityCatalogInventoryItem "{5D728AAF0D0B5BD1}" {
     m_bEnabled 0
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{6556B93BF51CD869}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{66FD3E333D9CEC95}" {
     m_sEntityPrefab "{184DFCEFE574E775}Prefabs/Items/Equipment/Tripods/6T7/Part_NSV_Gun.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{61ECC6DC8DB987BC}" {
       m_eItemType EQUIPMENT
       m_eItemMode SUPPORT_STATION
       m_iSupplyCost 80
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66FD3E3322AC0D22}" {
     m_sEntityPrefab "{184DFCEFE574E776}Prefabs/Items/Equipment/Tripods/6T7/Part_NSV_Tripod.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6556A2FFDA3E5050}" {
       m_eItemType EQUIPMENT
       m_eItemMode SUPPORT_STATION
       m_iSupplyCost 40
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66FD3E3322738961}" {
     m_sEntityPrefab "{F6490587042BFEE5}Prefabs/Items/Equipment/Tripods/PKM/Part_Tripod_6T5.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6556B93BD7B6E13B}" {
       m_eItemType EQUIPMENT
       m_eItemMode SUPPORT_STATION
       m_iSupplyCost 30
       m_eRequiredRank CORPORAL
      }
     }
    }
   }
  }
 }
}