SCR_EntityCatalog {
 m_eEntityCatalogType WEAPONS_TRIPOD
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{69F2980475511849}" {
   m_sEntityPrefab "{723870DBB19D30B0}Prefabs/Weapons/Tripods/Tripod_6T5_PKM.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69F2980475511854}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{69F2980475511856}" {
   m_sEntityPrefab "{29F0CC704A582154}Prefabs/Weapons/Tripods/6T7/Tripod_6T7_NSV.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69F2980475511857}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{69F2980475511858}" {
   m_sEntityPrefab "{3EA26CFD7A202636}Prefabs/Weapons/Tripods/6T7/Tripod_6T7_NSV_SPP.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69F2980475511859}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{69F298047551F619}" {
   m_sEntityPrefab "{D1FFE458E8AC4BDB}Prefabs/Weapons/Mortars/2B14/Mortar_2B14.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69F298047551F61B}" {
    }
   }
  }
 }
}