SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{671CE53490C67ADD}" {
   m_sEntityPrefab "{2612E1A7DD2F4DFE}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_30rnd_Ball.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{669F2DD8A564AB73}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE5349390040A}" {
   m_sEntityPrefab "{B11727710EC12776}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_30rnd_Last_5Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{669F2DD8A4445614}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE5349254B3AC}" {
   m_sEntityPrefab "{811F098714578F82}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_30rnd_Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{669F2DD8A741524C}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE53492EE362B}" {
   m_sEntityPrefab "{0E20F7714BF9F2D5}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_30rnd_Subsonic.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6718C3497E7E63A9}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 5
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534AD794A80}" {
   m_sEntityPrefab "{3C9A4D3905B2C0A1}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_30rnd_Bakelite_Ball.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66CED00D8561DCFA}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534AC1786F1}" {
   m_sEntityPrefab "{B2285E76167B4AAA}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_30rnd_Bakelite_Last_5Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66CED00D84098DA3}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534ACD62826}" {
   m_sEntityPrefab "{C1D83071BA2ACC7C}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_30rnd_Bakelite_Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66CED00D84A36D6F}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534AF861268}" {
   m_sEntityPrefab "{04059D7F987013EE}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_30rnd_Bakelite_Subsonic.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6718C34976C85D16}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 5
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534AE20BC20}" {
   m_sEntityPrefab "{B74501AFC4A93758}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_40rnd_Steel_Ball.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66CF509449DA4998}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534AECDD344}" {
   m_sEntityPrefab "{FA95A7DF7048AB33}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_40rnd_Steel_4B1TMix.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66CF50944416DEE1}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671CE534A993D8FC}" {
   m_sEntityPrefab "{AB52A62B8DAC9003}Prefabs/Weapons/Magazines/ARY_AKM/ARY_Magazine_762x39_AKM_40rnd_Steel_Tracer.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66CF509441094E11}" {
     m_eItemMode AMMUNITION
     m_iSupplyCost 2
     m_eRequiredRank CORPORAL
    }
   }
  }
 }
}