SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{671CE53498D84696}" {
   m_sEntityPrefab "{5CE97E5867E678BE}Prefabs/Weapons/Attachments/ARY_AKM_Components/ARY_Topcover_AK47.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6716F87A20E7E758}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 8
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671D3B6E57080BEE}" {
   m_sEntityPrefab "{63D54CD72029E7E4}Prefabs/Weapons/Attachments/ARY_AKM_Components/ARY_Topcover_AKM.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{671D3B6E57080BA5}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 8
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671D3B6E54130AE7}" {
   m_sEntityPrefab "{009FC263942884E7}Prefabs/Weapons/Attachments/Muzzle/ARY_ThreadProtector_AK47/ARY_ThreadProtector_AK47.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{671D3B6E54130A5A}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 8
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671D3B6E5BB6934A}" {
   m_sEntityPrefab "{65A7741FD7CFEC2B}Prefabs/Weapons/Attachments/Muzzle/ARY_FlashHider_AKM/ARY_FlashHider_AKM.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{671D3B6E5BB69306}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 8
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{671D3B6E58182D10}" {
   m_sEntityPrefab "{268B34E6CCE3C21B}Prefabs/Weapons/Attachments/Muzzle/ARY_Suppressor_PBS1/ARY_Suppressor_PBS1.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{671D3B6E581822BD}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 8
     m_eRequiredRank LIEUTENANT
    }
   }
  }
 }
}