SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{6120944188213139}" {
     m_bEnabled 1
    }
   }
  }
 }
}