SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6592D685AB22595C}" {
   m_sEntityPrefab "{99D3D64BDB9B252C}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_HeliPilot_M9SD.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6592D685AB225997}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{6597536457B20915}" {
   m_sEntityPrefab "{B524086E16897EBF}Prefabs/Characters/Factions/BLUFOR/US_Army/Character_US_HeliPilot_M9SD_nonGM.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6597536457B20989}" {
    }
   }
  }
 }
}