SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AB9FBDDC}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5C62F7D8ECAFAAA3}" {
     m_sEntityPrefab "{E656525AFDC8275A}Prefabs/Weapons/Handguns/M9/Handgun_M9_Threaded_Barrel.et"
    }
    SCR_EntityCatalogInventoryItem "{659378E49A95F493}" {
     m_sEntityPrefab "{7FEE5ADE11EE4B88}Prefabs/Weapons/Handguns/M9/Handgun_M9_Threaded_Barrel_Suppressed.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C62F7D84AAB75D4}" {
       m_iSupplyCost 10
       m_eRequiredRank CORPORAL
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA6FA1B8}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{5C62F7D8EBC8251B}" {
     m_sEntityPrefab "{3E7290C7DE244E9C}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_M882.et"
    }
    SCR_EntityCatalogInventoryItem "{659378E70A5C0F50}" {
     m_sEntityPrefab "{E49B006AD548A1A6}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_Tracer_Incendiary.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C62F7D848E8A152}" {
       m_iSupplyCost 6
       m_eRequiredRank CAPTAIN
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{659378E71B5653C9}" {
     m_sEntityPrefab "{51634695D45C3094}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_DM11_A1B2.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C62F7D848E8A152}" {
       m_iSupplyCost 5
       m_eRequiredRank CAPTAIN
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{659378E71536D85C}" {
     m_sEntityPrefab "{F1C6470E23888704}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_MK_243_MOD_0.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C62F7D848E8A152}" {
       m_iSupplyCost 4
       m_eRequiredRank CAPTAIN
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{659378E4F88FC915}" {
     m_sEntityPrefab "{3C5F0911AD27A66C}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_M1153.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C62F7D848E8A152}" {
       m_iSupplyCost 3
       m_eRequiredRank LIEUTENANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{659378E4CF44AEFE}" {
     m_sEntityPrefab "{D9C345E8A1C23107}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_M1152.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C62F7D848E8A152}" {
       m_iSupplyCost 2
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{659378E4DF940FD5}" {
     m_sEntityPrefab "{9E5F652C9E02CA36}Prefabs/Weapons/Magazines/Magazine_9x19_M9_15rnd_M874.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{5C62F7D848E8A152}" {
       m_iSupplyCost 2
       m_eRequiredRank CORPORAL
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA315A22}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{659378E72CD1E047}" {
     m_sEntityPrefab "{3F03889FAC7EBF77}Prefabs/Weapons/Attachments/Muzzle/Suppressor_M9/Suppressor_M9.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{659378E72CD1E0FD}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 5
       m_eRequiredRank CORPORAL
      }
     }
    }
   }
  }
 }
}