SCR_EntityCatalog {
 m_eEntityCatalogType WEAPONS_TRIPOD
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{5C54F92F74CEE665}" {
   m_sEntityPrefab "{723870DBB19D30B0}Prefabs/Weapons/Tripods/Tripod_6T5_PKM.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{605697813CAC7EDA}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{605EC3F4D33395C6}" {
   m_sEntityPrefab "{29F0CC704A582154}Prefabs/Weapons/Tripods/6T7/Tripod_6T7_NSV.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{605EC7F8A3639B48}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{605EC3F4D42E1B0A}" {
   m_sEntityPrefab "{3EA26CFD7A202636}Prefabs/Weapons/Tripods/6T7/Tripod_6T7_NSV_SPP.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{605EC7F8AF736074}" {
    }
   }
  }
  SCR_EntityCatalogEntry "{6198E4353E9E5B5E}" {
   m_sEntityPrefab "{D1FFE458E8AC4BDB}Prefabs/Weapons/Mortars/2B14/Mortar_2B14.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6198E4353CB215A2}" {
    }
   }
  }
 }
}