SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{66130A0D3723A3BC}" {
   m_sEntityPrefab "{846997F496AA067B}Prefabs/Weapons/Rifles/ARY_G3/ARY_G3_G3KA3/ARY_Rifle_G3KA3.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66130A0D3723A36A}" {
     m_eItemMode WEAPON
     m_iSupplyCost 16
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66130A0D3723A36C}" {
       m_vItemOffset 0 0.04 -0.13
      }
     }
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66130A0D348E5EFA}" {
   m_sEntityPrefab "{C05B71F1A8531BE3}Prefabs/Weapons/Rifles/ARY_G3/ARY_G3_G3KA4/ARY_Rifle_G3KA4.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66130A0D348E5EA4}" {
     m_eItemMode WEAPON
     m_iSupplyCost 18
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66130A0D348E5EA6}" {
       m_vItemOffset 0 0 -0.38
      }
     }
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66130A0D35E1D938}" {
   m_sEntityPrefab "{04331D36864C0AEC}Prefabs/Weapons/Rifles/ARY_G3/ARY_G3_MC51/ARY_Rifle_MC51A3.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66130A0D35E1D8FD}" {
     m_eItemMode WEAPON
     m_iSupplyCost 20
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66130A0D35E1D8FF}" {
       m_vItemOffset 0 0 -0.15
      }
     }
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66130A0D3528AF52}" {
   m_sEntityPrefab "{3907380EF32083DB}Prefabs/Weapons/Rifles/ARY_G3/ARY_G3_MC51/ARY_Rifle_MC51A4.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66130A0D3528AF39}" {
     m_eItemMode WEAPON
     m_iSupplyCost 22
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66130A0D3528AF3B}" {
       m_vItemOffset 0 0 -0.38
      }
     }
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{6624DEC739C94237}" {
   m_sEntityPrefab "{986BEF5334508006}Prefabs/Weapons/Rifles/ARY_G3/ARY_G3_MC51/ARY_Rifle_MC51SD4.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6624DEC739C94599}" {
     m_eItemMode WEAPON
     m_iSupplyCost 22
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{6624DEC739C9459C}" {
       m_vItemOffset 0 0 -0.38
      }
     }
     m_eRequiredRank MAJOR
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66130A0D3BD458BD}" {
   m_sEntityPrefab "{91123A35DE90EF32}Prefabs/Weapons/Rifles/ARY_G3/ARY_PSG1/ARY_Rifle_G3_PSG1_Scoped.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66130A0D3BD45ED4}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON
     m_iSupplyCost 30
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66130A0D3BD45ECA}" {
       m_vItemOffset 0 0.04 -0.13
      }
     }
     m_eRequiredRank LIEUTENANT
    }
   }
  }
 }
}