SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453CE20F8F}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{665B1AF4EC4A8B00}" {
     m_sEntityPrefab "{DC4B73FD0B1E8816}Prefabs/Weapons/Handguns/ARY_1911/ARY_Handgun_1911_Worn.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{661A9DB36C88624C}" {
       m_eItemType PISTOL
       m_eItemMode WEAPON
       m_iSupplyCost 5
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{661A9DB36C886241}" {
        }
       }
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C630E4538D3163D}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{665B1AF4DA84E98D}" {
     m_sEntityPrefab "{81563D558B5BCF69}Prefabs/Weapons/Magazines/ARY_Magazine_45acp_1911_7rnd.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{661A9DB35C41C341}" {
       m_eItemType PISTOL
       m_eItemMode AMMUNITION
       m_iSupplyCost 1
      }
     }
    }
   }
  }
 }
}