SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C630E453CE20F8F}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{696E781B087C34BA}" {
     m_sEntityPrefab "{7121DDCD2E542E88}Prefabs/Weapons/Rifles/ARY_HarrySingleShotgun/ARY_Shotgun_HarrySingleShot.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{667330FBE0CAE6B5}" {
       m_eItemMode WEAPON
       m_iSupplyCost 5
       m_aArsenalDisplayData {
        SCR_ArsenalItemDisplayData "{667330FBE0CAE6B7}" {
         m_vItemOffset 0 0.07 -0.25
        }
       }
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C630E4538D3163D}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{696E781B077B7D42}" {
     m_sEntityPrefab "{7784394BECA5FA0C}Prefabs/Weapons/Ammo/ARY_ShotgunShells/ARY_ShotgunShell_12Ga_Birdshot.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{696B4229E2F05B58}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{696E781B0130C682}" {
     m_sEntityPrefab "{1D766111E1521F32}Prefabs/Items/Equipment/ARY_AmmoBox_ShotgunShells/ARY_AmmoBox_ShotgunShells_Birdshot.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{696E781B566D4F27}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{696E781B00008E42}" {
     m_sEntityPrefab "{054D7FB5F7CD3A25}Prefabs/Weapons/Ammo/ARY_ShotgunShells/ARY_ShotgunShell_12Ga_Buckshot.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{696B4229E7AFB843}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 1
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{696E781B0304F207}" {
     m_sEntityPrefab "{06C4FDE801964BA1}Prefabs/Items/Equipment/ARY_AmmoBox_ShotgunShells/ARY_AmmoBox_ShotgunShells_Buckshot.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{696E781B673B2EAD}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 1
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{696E781B03BD4CB4}" {
     m_sEntityPrefab "{986FF17F666A0EFF}Prefabs/Weapons/Ammo/ARY_ShotgunShells/ARY_ShotgunShell_12Ga_Slug.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{696B4229FDB3CDAA}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 1
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{696E781B0287E073}" {
     m_sEntityPrefab "{7ABD14E71A8AC824}Prefabs/Items/Equipment/ARY_AmmoBox_ShotgunShells/ARY_AmmoBox_ShotgunShells_Slug.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{696E781B66071F4E}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 1
       m_eRequiredRank SERGEANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69A94252BA2DB729}" {
     m_sEntityPrefab "{E7F3057EBF04B6CA}Prefabs/Weapons/Ammo/ARY_ShotgunShells/ARY_ShotgunShell_12Ga_Buckshot_Tracer.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69A94252BA2DB6EE}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 1
       m_eRequiredRank LIEUTENANT
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{69A94252BB443305}" {
     m_sEntityPrefab "{6F82952F2D361E87}Prefabs/Items/Equipment/ARY_AmmoBox_ShotgunShells/ARY_AmmoBox_ShotgunShells_Bucktracer.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{69A94252BB4432F4}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 1
       m_eRequiredRank LIEUTENANT
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{5C630E453CA0B981}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{698900A0D914FECF}" {
     m_sEntityPrefab "{AFA466D9615621E9}Prefabs/Weapons/Attachments/Bayonets/Knife_Bayonet.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{698900A0D914FD15}" {
       m_eItemType WEAPON_ATTACHMENT
       m_eItemMode ATTACHMENT
       m_iSupplyCost 0
      }
     }
    }
   }
  }
 }
}