SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EE815FA292}" {
   m_eEntityCatalogType NONE
  }
  SCR_EntityCatalogMultiList "{5C9E82F29B327997}" {
   m_eEntityCatalogType NONE
  }
  SCR_EntityCatalogMultiList "{5C68A0EE8B97CA50}" {
   m_eEntityCatalogType NONE
  }
  SCR_EntityCatalog "{5C68A0EEB7DB3E84}" {
   m_eEntityCatalogType NONE
  }
  SCR_EntityCatalogMultiList "{5C68A0EEB3F124F9}" {
   m_eEntityCatalogType NONE
  }
  SCR_EntityCatalog "{5C9EDDD37394AD40}" {
   m_eEntityCatalogType NONE
  }
 }
}