SCR_Faction : "{B122E3B10BB3404B}Configs/Factions/OPFOR.conf" {
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0E9BD5E5DD9}" {
   m_eEntityCatalogType NONE
  }
  SCR_EntityCatalogMultiList "{5C9E82F285C09E24}" {
   m_eEntityCatalogType NONE
  }
  SCR_EntityCatalogMultiList "{5C68A0E9B9AA3C2D}" {
   m_eEntityCatalogType NONE
  }
  SCR_EntityCatalog "{5C68A0E9A51460AB}" {
   m_eEntityCatalogType NONE
  }
  SCR_EntityCatalogMultiList "{5C68A0E9AFE1E631}" {
   m_eEntityCatalogType NONE
  }
 }
}