SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{667330FBC23EC256}" {
   m_sEntityPrefab "{386D76E51396F48D}Prefabs/Characters/Factions/BLUFOR/US_Army/ARY_Character_US_GL_M79.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{667330FBC23EC20D}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{667330FBC23EC20F}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{667330FBDC915585}" {
   m_sEntityPrefab "{B582EE3C0979D35B}Prefabs/Characters/Factions/BLUFOR/US_Army/GreenBerets/ARY_Character_US_SF_GL_M79.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{667330FBDC91557F}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{667330FBDC915572}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}