SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{5C68AD59AA1A6D59}" {
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{66AB30A86EAF9D57}" {
     m_sEntityPrefab "{7E06757D25934EBA}Prefabs/Characters/Footwear/ARY_FROCS_01_White.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AB30A86EAF9D0F}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66AB30A82BBEBE2A}" {
     m_sEntityPrefab "{494DB76EE9B7B912}Prefabs/Characters/Footwear/ARY_FROCS_01_Beige.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AB30A82BBEB199}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66AB30A813D5537E}" {
     m_sEntityPrefab "{E6D595DF462653EC}Prefabs/Characters/Footwear/ARY_FROCS_01_OD.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AB30A813D55330}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
       m_eRequiredRank CORPORAL
      }
     }
    }
    SCR_EntityCatalogInventoryItem "{66AB30A86BD3E769}" {
     m_sEntityPrefab "{B6E6778FE0EA0E70}Prefabs/Characters/Footwear/ARY_FROCS_01_Black.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{66AB30A86BD3E72A}" {
       m_eItemType FOOTWEAR
       m_iSupplyCost 0
       m_eRequiredRank SERGEANT
      }
     }
    }
   }
  }
 }
}