SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697826E2AC672}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{5E6A970D0BA5CB44}" {
    }
    SCR_EntityCatalogEntry "{5E6A970D627F6ECB}" {
    }
    SCR_EntityCatalogEntry "{5E6A970D8EFEFC75}" {
    }
    SCR_EntityCatalogEntry "{5E6A970DBBA132B4}" {
    }
    SCR_EntityCatalogEntry "{5E6A970DA225BFE9}" {
    }
    SCR_EntityCatalogEntry "{5E6A970DADE54E4C}" {
    }
    SCR_EntityCatalogEntry "{5E6A970DD355F70A}" {
    }
    SCR_EntityCatalogEntry "{5E6A970DC468CBCF}" {
    }
    SCR_EntityCatalogEntry "{5E6A970DCEF3349E}" {
    }
    SCR_EntityCatalogEntry "{5E6A970DF4E2FC88}" {
    }
    SCR_EntityCatalogEntry "{5E6A970DFB1A3EF6}" {
    }
    SCR_EntityCatalogEntry "{5E6A970DE547D3FF}" {
    }
    SCR_EntityCatalogEntry "{5F1EC40E1C0E4442}" {
    }
    SCR_EntityCatalogEntry "{6056FB19E2DFC099}" {
    }
    SCR_EntityCatalogEntry "{6056FB19F9DBF84B}" {
    }
    SCR_EntityCatalogEntry "{6056FB19F9618610}" {
    }
    SCR_EntityCatalogEntry "{6056FB19A7DA5677}" {
    }
    SCR_EntityCatalogEntry "{6056FB19A69B5355}" {
    }
    SCR_EntityCatalogEntry "{6056FB19A51FAA7E}" {
    }
    SCR_EntityCatalogEntry "{6056FB19A4C29AF8}" {
    }
    SCR_EntityCatalogEntry "{6082C972462F2F29}" {
    }
   }
  }
 }
}