SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{663525FA8FCC1533}" {
   m_sEntityPrefab "{9EFBCD4E87A7A29B}Prefabs/Weapons/Rifles/ARY_M14/ARY_Rifle_M14.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{661A9DB3530F876C}" {
     m_eItemMode WEAPON
     m_iSupplyCost 20
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{661A9DB3530F876E}" {
       m_vItemOffset 0 0.04 -0.25
       m_vItemRotation -4 0 0
      }
     }
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66C53364AB621FCF}" {
   m_sEntityPrefab "{0B5C5BBBC46C26A6}Prefabs/Weapons/Rifles/ARY_M14/ARY_Rifle_M14_OpticMount.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C53364AB621FAA}" {
     m_eItemMode WEAPON
     m_iSupplyCost 20
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66C53364AB621FAC}" {
       m_vItemOffset 0 0.04 -0.25
       m_vItemRotation -4 0 0
      }
     }
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663525FA8E58533A}" {
   m_sEntityPrefab "{941661DC89361501}Prefabs/Weapons/Rifles/ARY_M14/ARY_Rifle_M14_OliveGreen.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6619297F5C51A645}" {
     m_eItemMode WEAPON
     m_iSupplyCost 20
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{6619297F5C51A646}" {
       m_vItemOffset 0 0.04 -0.25
       m_vItemRotation -4 0 0
      }
     }
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66C53364A8AB9F4B}" {
   m_sEntityPrefab "{6360BCDE6A998D27}Prefabs/Weapons/Rifles/ARY_M14/ARY_Rifle_M14_OpticMount_OliveGreen.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C53364A8AB9F28}" {
     m_eItemMode WEAPON
     m_iSupplyCost 20
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66C53364A8AB9F2B}" {
       m_vItemOffset 0 0.04 -0.25
       m_vItemRotation -4 0 0
      }
     }
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663525FA8EE92808}" {
   m_sEntityPrefab "{D7D7FC19D67CD5AF}Prefabs/Weapons/Rifles/ARY_M14/ARY_Rifle_M14_SandStripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6619297F54B2037E}" {
     m_eItemMode WEAPON
     m_iSupplyCost 20
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{6619297F54B20370}" {
       m_vItemOffset 0 0.04 -0.25
       m_vItemRotation -4 0 0
      }
     }
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66C53364A8054C4B}" {
   m_sEntityPrefab "{A990D456ABE49F16}Prefabs/Weapons/Rifles/ARY_M14/ARY_Rifle_M14_OpticMount_SandStripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C53364A8054C32}" {
     m_eItemMode WEAPON
     m_iSupplyCost 20
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66C53364A8054C34}" {
       m_vItemOffset 0 0.04 -0.25
       m_vItemRotation -4 0 0
      }
     }
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{664E98C02FCF6FF8}" {
   m_sEntityPrefab "{C4F22E845D68E559}Prefabs/Weapons/Rifles/ARY_M14/ARY_Rifle_M14_Worn.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{664E98C02FCF6FB6}" {
     m_eItemMode WEAPON
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{664E98C02FCF6FA8}" {
       m_vItemOffset 0 0.04 -0.25
       m_vItemRotation -4 0 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{66C53364A962D0B8}" {
   m_sEntityPrefab "{5D63AE1BB4CA41EC}Prefabs/Weapons/Rifles/ARY_M14/ARY_Rifle_M14_Worn_OpticMount.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{66C53364A962D062}" {
     m_eItemMode WEAPON
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{66C53364A962D064}" {
       m_vItemOffset 0 0.04 -0.25
       m_vItemRotation -4 0 0
      }
     }
    }
   }
  }
 }
}