SCR_EntityCatalogMultiListEntry {
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{663525FA807809C8}" {
   m_sEntityPrefab "{1D82FDB6A2FAC4BA}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k_M14Mount_Black.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{662B241634A6F40E}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663525FA83155C29}" {
   m_sEntityPrefab "{4B3D32257667ED48}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k_M14Mount_SIlver.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{662B2417C259A730}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663525FA83AD5166}" {
   m_sEntityPrefab "{56DE1FF7DCEE0B65}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k_M14Mount_Camo_OD.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{662B2417DF1FECC9}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663525FA82EF8FD3}" {
   m_sEntityPrefab "{BECE58527660C538}Prefabs/Weapons/Attachments/Optics/ARY_Optic_AP3k/ARY_Collim_AP3k_M14Mount_Camo_Sand.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{662B2417DFEDD5DC}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_eRequiredRank LIEUTENANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{663525FA9DBA2464}" {
   m_sEntityPrefab "{9984078C497EDF5A}Prefabs/Weapons/Attachments/Bayonets/ARY_Bayonet_M6.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{6631014C09AFFBD4}" {
     m_eItemType WEAPON_ATTACHMENT
     m_eItemMode ATTACHMENT
     m_iSupplyCost 0
     m_eRequiredRank SERGEANT
    }
   }
  }
 }
}