SCR_EntityCatalogMultiList "{BB12292052E2F5B8}Configs/EntityCatalog/FactionLess/InventoryItems_EntityCatalog_Factionless.conf" {
 m_eEntityCatalogType ITEM
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{621AA63A70D132BF}" {
   m_sIdentifier "Other"
   m_aEntities {
    SCR_EntityCatalogInventoryItem "{621AA63A7D8E23A3}" {
     m_sEntityPrefab "{E7FF723379730BD5}Prefabs/Items/PersonalBelongings/PersonalBelongings_CIV.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{6134C335A739DC92}" {
       m_eItemType EQUIPMENT
       m_iSupplyCost 0
      }
      SCR_EntityCatalogIdentityItemData "{621AA6322637D5AA}" {
      }
     }
    }
   }
  }
 }
}